
set_property IOSTANDARD LVCMOS33 [get_ports {speedOut[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {speedOut[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {speedOut[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {speedOut[0]}]
set_property PACKAGE_PIN R14 [get_ports {speedOut[0]}]
set_property PACKAGE_PIN P14 [get_ports {speedOut[1]}]
set_property PACKAGE_PIN N16 [get_ports {speedOut[2]}]
set_property PACKAGE_PIN M14 [get_ports {speedOut[3]}]
set_property PACKAGE_PIN H16 [get_ports clock]
set_property PACKAGE_PIN D19 [get_ports reset]
set_property PACKAGE_PIN Y14 [get_ports black]
set_property PACKAGE_PIN T11 [get_ports brown]
set_property PACKAGE_PIN T10 [get_ports red]
set_property PACKAGE_PIN W14 [get_ports white]
set_property PACKAGE_PIN V16 [get_ports draw]
set_property PACKAGE_PIN V12 [get_ports erase]
set_property PACKAGE_PIN W13 [get_ports gameRst]
set_property PACKAGE_PIN L20 [get_ports speedInc]
set_property PACKAGE_PIN L19 [get_ports speedDec]
set_property IOSTANDARD LVCMOS33 [get_ports black]
set_property IOSTANDARD LVCMOS33 [get_ports brown]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports dc]
set_property IOSTANDARD LVCMOS33 [get_ports draw]
set_property IOSTANDARD LVCMOS33 [get_ports erase]
set_property IOSTANDARD LVCMOS33 [get_ports gameRst]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports res]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports speedDec]
set_property IOSTANDARD LVCMOS33 [get_ports speedInc]
set_property IOSTANDARD LVCMOS33 [get_ports white]
create_clock -period 8.000 -name sys_clk -waveform {0.000 4.000} [get_ports clock]
set_property PACKAGE_PIN M20 [get_ports sw]
set_property IOSTANDARD LVCMOS33 [get_ports sw]
set_property PACKAGE_PIN U18 [get_ports cs]
set_property PACKAGE_PIN Y17 [get_ports dc]
set_property PACKAGE_PIN Y16 [get_ports res]
set_property PACKAGE_PIN Y18 [get_ports sck]
set_property PACKAGE_PIN Y19 [get_ports sda]


